project: fastapi-uv

# Set this if you want to carry over parent process' environment variables
# carry_env: true

#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development

#
# Providers
#
providers:
  # you can mix and match many files
  dotenv:
    env_sync:
      path: ~/my-dot-env.env
    env:
      FOO_BAR:
        path: ~/my-dot-env.env

  # Configure via environment variables:
  # OP_CONNECT_HOST
  # OP_CONNECT_TOKEN
  1password:
    env_sync:
      path: # Key title
      source: # 1Password token gen include access to multiple vault. to get the secrets you must add and vaultUUID. the field is mandatory
    env:
      FOO_BAR:
        path: # Key title
        source: # 1Password token gen include access to multiple vault. to get the secrets you must add and vaultUUID. the field is mandatory
        field: # The secret field to get. notesPlain, {label key}, password etc.
