site_name: fastapi-uv
repo_url: https://github.com/acola/fastapi-uv
site_url: https://acola.github.io/fastapi-uv
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: AC
edit_uri: edit/main/docs/
repo_name: acola/fastapi-uv
copyright: Maintained by <a href="https://kubernetista.io">Kubernetista</a>

nav:
  - Home: index.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/fastapi_uv]

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acola/fastapi-uv
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fastapi-uv

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - src/fastapi_uv/main.py
  - docs/
